language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
branches:
  only:
    - master
    - develop
script:
  - export CODECOVERAGE=1; vendor/bin/phpunit --coverage-clover=clover.xml
before_script:
  - composer install --prefer-dist --no-interaction
after_success:
  - bash <(curl -s https://codecov.io/bash)
