language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly
branches:
  only:
    - master
    - develop
before_script:
  - composer install --prefer-dist --no-interaction
after_success:
  - bash <(curl -s https://codecov.io/bash);
